<?php

namespace Almooradi\FilamentEcommerce\Database\seeders;

use Almooradi\FilamentEcommerce\Constants\CategoryStatus;
use Almooradi\FilamentEcommerce\Constants\Gender;
use Almooradi\FilamentEcommerce\Constants\ProductStatus;
use Almooradi\FilamentEcommerce\Models\Product\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        Product::insert([
            [
                'title' => 'Skin care with vanilla extract',
                'slug' => 'skin-care-with-vanilla-extract',
                'short_description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, and it includes oil',
                'gender' => Gender::UNISEX,
                'show_in' => '["home"]',
                'status' => ProductStatus::PUBLISHED,
                'media_files' => '["shop/products/tNAgzkrdhaiyP6R1qcn7SvV5A5YuI6-metaYW5pcy1tLVduVnJPLUR2eGNFLXVuc3BsYXNoLmpwZw==-.jpg","shop/products/KkFQBMDeRTK4Vp4SPf8caxE8yeoKQe-metab25uZS1iZWF1dHktbFo3dGFvNzlZMUEtdW5zcGxhc2guanBn-.jpg"]',
                'highlight_label_background_color' => null,
                'highlight_label_text_color' => null,
                'highlight_label_text' => null,
                'quantity' => null,
                'price' => '10',
                'discount_type' => 'none',
                'discount_amount' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title' => 'Milk soap and olive oil',
                'slug' => 'milk-soap-and-olive-oil',
                'short_description' => null,
                'gender' => Gender::UNISEX,
                'show_in' => '["home"]',
                'status' => ProductStatus::PUBLISHED,
                'media_files' => '["shop/products/eeDzHCilWlDsXxGQdI6hLpKyzO9pNA-metabmF0dXJhbC1nMGIxZTVmNWEyXzY0MC5qcGc=-.jpg"]',
                'highlight_label_background_color' => null,
                'highlight_label_text_color' => null,
                'highlight_label_text' => null,
                'quantity' => null,
                'price' => '12',
                'discount_type' => 'fixed',
                'discount_amount' => '2',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title' => 'Olive oil shampoo & milk for women',
                'slug' => 'olive-oil-shampoo-milk-for-women',
                'short_description' => null,
                'gender' => Gender::MALE,
                'show_in' => '["home"]',
                'status' => ProductStatus::PUBLISHED,
                'media_files' => '["shop/products/8E3w3m2ud2MG3FIbTAFslY9GSGPTof-metaV29tYW4gLSA1ODE0Mi5tcDQ=-.mp4"]',
                'highlight_label_background_color' => null,
                'highlight_label_text_color' => null,
                'highlight_label_text' => null,
                'quantity' => null,
                'price' => null,
                'discount_type' => 'none',
                'discount_amount' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title' => 'Hydra Genius Waters Moisturizer Normal to Combination Skin 70 ML',
                'slug' => 'hydra-genius-waters-moisturizer-normal-to-combination-skin-70-ml',
                'short_description' => null,
                'gender' => Gender::MALE,
                'show_in' => '[]',
                'status' => ProductStatus::PUBLISHED,
                'media_files' => null,
                'highlight_label_background_color' => null,
                'highlight_label_text_color' => null,
                'highlight_label_text' => null,
                'quantity' => null,
                'price' => null,
                'discount_type' => 'none',
                'discount_amount' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title' => 'Skin Active Eye Mask',
                'slug' => 'skin-active-eye-mask',
                'short_description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters',
                'gender' => Gender::FEMALE,
                'show_in' => '["home"]',
                'status' => ProductStatus::PUBLISHED,
                'media_files' => '["shop/products/D7XtWEQKEChoyxM42oLvQrh5q1ythH-metaYm90dGxlLWc5ZTJlYzg5MTRfNjQwLmpwZw==-.jpg","shop/products/obu9bpKJ1DW0FsftNremasdiCYyZ0i-metaYW5pcy1tLVduVnJPLUR2eGNFLXVuc3BsYXNoLmpwZw==-.jpg","shop/products/m1ZGyKsfU0K3rMFMtEGylvRvXTIxYg-metaYmVueWFmZXotc3R1ZGlvLWhIRC1LbV9vT0RJLXVuc3BsYXNoLmpwZw==-.jpg","shop/products/E8UCPKqq7xgbX8PM2wGp1TSr6pXzob-metaamFjaW50YS1jaHJpc3Rvcy00d081R09OM21nNC11bnNwbGFzaC5qcGc=-.jpg","shop/products/bHniDV8npOeSJh6Eii551exox8kFYG-metabWlza2Etc2FnZS1xZmNYeUczY1VKOC11bnNwbGFzaC5qcGc=-.jpg","shop/products/s5Cctbhc7lDLiu6reDrBYDceMI3RSr-metabmF0dXJhbC1nMGIxZTVmNWEyXzY0MC5qcGc=-.jpg","shop/products/6Lq55v1HmplnnWkhAz1ugolypAkP13-metab25uZS1iZWF1dHktbFo3dGFvNzlZMUEtdW5zcGxhc2guanBn-.jpg","shop/products/ExaujmoaUls0sXo32T9BDls1tVj869-metadnlhLW5hdHVyYWxzLVdiRkZOcUhLQmlZLXVuc3BsYXNoLmpwZw==-.jpg"]',
                'highlight_label_background_color' => '#10562c',
                'highlight_label_text_color' => '#ffffff',
                'highlight_label_text' => 'Special',
                'quantity' => null,
                'price' => '10',
                'discount_type' => 'none',
                'discount_amount' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title' => 'Beesline Roll-On Deodorant Fragrance Free 50 ML',
                'slug' => 'beesline-roll-on-deodorant-fragrance-free-50-ml',
                'short_description' => null,
                'gender' => Gender::FEMALE,
                'show_in' => '["home"]',
                'status' => ProductStatus::PUBLISHED,
                'media_files' => '["shop/products/2tQSy1HbXD3PQmwG5UQ0MtaaS69Gf3-metabWlza2Etc2FnZS1xZmNYeUczY1VKOC11bnNwbGFzaC5qcGc=-.jpg"]',
                'highlight_label_background_color' => null,
                'highlight_label_text_color' => null,
                'highlight_label_text' => null,
                'quantity' => null,
                'price' => '20',
                'discount_type' => 'none',
                'discount_amount' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title' => 'Express Facial Super Moisture Mask',
                'slug' => 'express-facial-super-moisture-mask',
                'short_description' => null,
                'gender' => Gender::MALE,
                'show_in' => '["home"]',
                'status' => ProductStatus::PUBLISHED,
                'media_files' => '["shop/products/YhRqQv7eBvlZHhRBdbRvlTAZrBMNte-metaYm90dGxlLWc5ZTJlYzg5MTRfNjQwLmpwZw==-.jpg"]',
                'highlight_label_background_color' => null,
                'highlight_label_text_color' => null,
                'highlight_label_text' => null,
                'quantity' => null,
                'price' => '50',
                'discount_type' => 'none',
                'discount_amount' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title' => 'Samoa Cotodou 80 + 40 FREE Disques',
                'slug' => 'samoa-cotodou-80-40-free-disques',
                'short_description' => null,
                'gender' => Gender::UNISEX,
                'show_in' => '["home"]',
                'status' => ProductStatus::PUBLISHED,
                'media_files' => '["shop/products/lLjtogw1DrpQzxSOlWmtrYEsy82prK-metab25uZS1iZWF1dHktbFo3dGFvNzlZMUEtdW5zcGxhc2guanBn-.jpg"]',
                'highlight_label_background_color' => null,
                'highlight_label_text_color' => null,
                'highlight_label_text' => null,
                'quantity' => null,
                'price' => '43',
                'discount_type' => 'none',
                'discount_amount' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'title' => 'Hyaluron Expert Day Cream SPF 20 - 50 ML',
                'slug' => 'hyaluron-expert-day-cream-spf-20-50-ml',
                'short_description' => null,
                'gender' => Gender::FEMALE,
                'show_in' => '["home"]',
                'status' => ProductStatus::PUBLISHED,
                'media_files' => '["shop/products/pzMWplBPGogb0hIIKZLFE3yossQpiL-metaamFjaW50YS1jaHJpc3Rvcy00d081R09OM21nNC11bnNwbGFzaC5qcGc=-.jpg"]',
                'highlight_label_background_color' => null,
                'highlight_label_text_color' => null,
                'highlight_label_text' => null,
                'quantity' => null,
                'price' => '43',
                'discount_type' => 'none',
                'discount_amount' => null,
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        ]);
    }
}
